import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'translate'
})
export class TranslatePipe implements PipeTransform {
  _wordBook = {
    'en': {
      'app_name': 'Appbuilder',
      'rmb': '¥',
      'pay_complete': 'Already finish  payment',
      'has_new_version': 'Having new version update or not',
      'app_version_is_new': 'The current version is the newest',
      'select_TA': 'Select Her',
      'select_guide': 'You have no shopping guide selected，come to choose one?',
      'login_success': 'Welcome back',
      'mobile_and_pwd_must_not_null': 'Mobile and PWD cannot be empty',
      'please_input_real_mobile': 'please input the mobile with right format',
      'password_must_between': 'The length of the PWD should between 6 and 12',
      'register_success': 'You have already registered success',
      'mobile_must_not_null': 'The mobile phone cannot be empty',
      'nickname_must_not_null': 'The nickname cannot be empty',
      'password_must_not_null': 'the PWD cannot be empty',
      'please_input_captcha': 'Please input the verification code',
      'nickname_must_between': 'The length of the nickname should between 2 and 12',
      'find_pwd_success': 'Look back PWD success',
      'pressed_again_exit': 'Press again to quit',
      'home_page': 'Index',
      'category': 'Category',
      'forum': 'Forum',
      'article': 'Article',
      'mine': 'Mine',
      'in_the_mood_for_love': 'In the mood for love',
      'share_app_content_before': 'I\'m using',
      'share_app_content_after': '，join us to sharing the our coupon',
      'wechat_client_not_installed': 'You do not install the client of Weixin yet',
      'share_to': 'Sharing to',
      'circle_of_friends': 'Friend circle',
      'qzone': 'QQ Zone',
      'please_pull_up_down_to_select_area': 'Please swipe up and down to choose the region',
      'cancel': 'Cancel',
      'good': 'Good',
      'sure': 'Confirm',
      'update': 'Update',
      'wechat': 'WeiXin',
      'tip': 'Tip',
      'day': 'Day',
      'hour': 'Hour',
      'minute': 'Minus',
      'second': 'Second',
      'delete': 'Delete',
      'net_error': 'Aha?The network is lost,please check your network and then click the screen',
      'no_data': 'No data get currently, please click to retry',
      'pay_success': 'Pay success',
      'user_has_cancel': 'User canceled',
      'not_pass_auth': 'Unautherized',
      'no_know_error': 'Unknown error',
      'pay_abnormal': 'Pay exception',
      'pay_cancel': 'Pay canceled',
      'user_data_update_success': 'User info have already updated',
      'please_select_the_provincial_information': 'please select the area',
      'please_fill_in_the_details': 'please inout the detail address',
      'please_fill_in_the_name_of_the_consignee': 'please input the name of the consignee',
      'please_contact_the_consignee': 'please input the phone of the consignee',
      'addr_name': 'Name',
      'addr_phone': 'Tel',
      'local_area': 'District',
      'detailed_address': 'Address',
      'default_address': 'Default Address',
      'delect_address': 'Delete Address',
      'save': 'Save',
      'addr_has_been_save': 'Saving shipping address  successfully',
      'addr_has_been_update': 'update shipping address successfully',
      'find': 'Find',
      'promotion': 'Promotion',
      'branch': 'Branch',
      'integral_mall': 'Credits Mall',
      'want_to_buy_something_today': 'Want to buy something today',
      'product_information': 'Product Info',
      'product_detail_all_comment_before': 'Product comment(',
      'product_detail_all_comment_after': ')',
      'graphic_details': 'Detail',
      'product_spec': 'Product Spec',
      'add_shop_car': 'Join Cart',
      'buy_immediately': 'Buy Now',
      'has_add_shop_car': 'Joined',
      'has_rob_count_before': 'Bought',
      'has_rob_count_after': 'Piece',
      'has_not_rob': 'Going to start',
      'has_rob': 'Staring',
      'has_rob_clear': 'Finished',
      'shop_car_product': 'Cart(product)',
      'shop_car_integral_mall': 'Cart(Credits Mall)',
      'product': 'Product',
      'shop_car_total': 'Total:',
      'not_ship': '(Not contain shipping fee)',
      'shop_car_settlement_before': 'Clearing(',
      'shop_car_settlement_after': ')',
      'this_product_has_delect': 'This product  deleted',
      'comment': 'Comment',
      'integral': 'Credits',
      'growth_value': 'Growth Score',
      'my_order': 'My Order',
      'my_shopping_guide': 'My shopping guide',
      'receipt_address': 'Shipping address',
      'my_post': 'My Post',
      'complaints_and_suggestions': 'Complaints and suggestions',
      'all': 'All',
      'not_paid': ' Not Paid',
      'already_paid': 'Paid',
      'payment_failure': 'Paid Failed',
      'already_shipped': 'Shipped',
      'cash_on_delivery': 'Pay on delivery ',
      'has_been_canceled': 'Canceled',
      'has_been_completed': 'Completed',
      'expired': 'Expired',
      'order_number': 'Order Number',
      'a_total_of_items_a_total_of_before': 'Total',
      'a_total_of_items_a_total_of_after': 'pieces of product\tTotal:',
      'freight': 'Contain shipping fee',
      'cancellation_of_order': 'Cancel Order',
      're_payment': 'Pay again',
      'confirm_receipt': 'Confirm Receipt',
      'delect_order': 'Delete order',
      'immediate_evaluation': 'Comment Now',
      'haven_not_received_the_goods_address_oh': 'You have no shipping address yet',
      'add_a_new_address': 'Add new address',
      'is_delect_the_address': 'Are you sure delete this address?',
      'is_cancel_order': 'Cancel this order?',
      'is_confirm_receipt': 'Confirm?',
      'is_delect_order': 'Sure to delete order',
      'setting': 'Setting',
      'about_store': 'About branch',
      'check_for_updates': 'Check Update',
      'wipe_cache': 'Clean cache',
      'set_share': 'Share to your friends,scan the QR code to download',
      'current_version': 'Current Version',
      'currently_is_the_latest_version': 'Current Version is the newest',
      'whether_to_clear_the_cache': 'Clean the cache or not',
      'growth': 'Growth score',
      'message': 'Message',
      'my_comments': 'My comments',
      'my_points': 'My credits',
      'current_level': 'Current level',
      'points_of_balance': 'The balance of the credits',
      'distance_to_the_next_level_before': 'Come to  the next level you need',
      'distance_to_the_next_level_after': 'growth scores',
      'click_on_the_header': 'Click the image to ask me',
      'change_guide': 'Change shopping guide',
      'message_remarks': 'message remark',
      'logistics_mode': 'Shipping type',
      'number_of_logistics': 'Shipping Order',
      'integral_number': 'Credits used',
      'sumulative_consumption_points': 'This order accumulate credits',
      'order_time': 'Order time',
      'real_payment': 'Actual Paid',
      'publish_hint': 'Publish',
      'dis': 'comment',
      'please_input_what_you_feedback': 'please input your content of the feedback',
      'send': 'Send',
      'title_activity_main': 'MainActivity',
      'title_activity_http': ' Network Requests',
      'title_activity_img_bower': 'ImgBowerActivity',
      'title_activity_pull_refresh': 'PullRefreshActivity',
      'title_activity_start': 'appbuilder',
      'title_activity_store_detail': 'Store Detail',
      'title_activity_product_detail': 'Product Detail',
      'title_activity_shop_cart': 'Shopping Cart',
      'title_activity_forget_password': 'Back PWD',
      'title_activity_login': 'Login',
      'title_activity_update_password': 'Modify PWD',
      'title_activity_register': 'Register',
      'title_activity_search': 'Search',
      'title_activity_forum_list': 'Topic Lists',
      'title_activity_publish_forum': 'Publish Topic',
      'title_activity_account_setting': 'Personal Setting',
      'title_activity_user_rank': 'Current Rank',
      'title_activity_user_order': 'My Order',
      'title_activity_user_address': 'Shipping Address',
      'title_activity_add_newAddress': 'Add New',
      'title_activity_modify_address': 'Edit Address',
      'title_activity_feedback': 'Complaint And Suggestion',
      'title_activity_userArticle': 'My Topics',
      'title_activity_choosePlace': 'Select Place',
      'title_activity_create_order': 'Commit Order',
      'title_activity_forumDetails': 'Topic Detail',
      'title_activity_articleDetails': 'Article Detail',
      'title_activity_shopGuide': 'Shopping Guide',
      'title_activity_chooseGuide': 'Choose Guide',
      'title_activity_userSetting': 'Setting',
      'title_activity_orderDetail': 'Order Detail',
      'title_activity_userCommit': 'My Comment',
      'title_activity_product_list': 'Product List',
      'title_activity_article_list': 'Article List',
      'title_activity_calendar': 'Select Date',
      'title_activity_my_member': 'My Members',
      'title_activity_commit_list': 'Comment List',
      'add_receipt_address': 'Add New',
      'modify_address_information': 'Edit Address',
      'the_receipt_address_has_been_deleted': 'This shipping address have been deleted',
      'comment_publish_success': 'Publish comment success',
      'current_points': 'Current Credits',
      'item_merchent_reply': 'Merchant  Reply',
      'the_posts_has_been_delect': 'This topic have already deleted',
      'only_normal_user_can_zan': 'Only the common user can thumb the topic',
      'only_normal_user_can_buy': 'Only the common user can shop',
      'only_normal_user_can_add_shop_cart': 'Only the common user can join to the shopping cart',
      'cancel_zan': 'Cancel Thumb',
      'has_been_zan': 'Thumbed',
      'number_of_participants': 'people joined',
      'post': 'topics',
      'replies': 'Reply the topic',
      'publish_post': 'Publish Topic',
      'thumb_number': 'people thumbed',
      'post_detail': 'Topic Detail',
      'all_post_comment_before': 'All Follow-up Comments(',
      'all_post_comment_after': ')',
      'activity_publish_post': 'Publish Topic',
      'publish_post_title_hint': 'Edit the topic title',
      'publish_post_content_hint': 'Edit the topic content',
      'classification': 'Category',
      'new_arrival': 'New products listing',
      'distance_events_start': 'Distance activity start:',
      'distance_events_end': 'Distance activity end::',
      'integral_not_enough': 'not enough credits',
      'convertible': 'Can Exchange',
      'please_input_mobile': 'please input the mobile',
      'please_input_password': 'please input the PWD with length between 6 and 12',
      'reg': 'Register',
      'only_ordinary_users_can_comment': 'Only the common user can publish comment',
      'only_ordinary_users_can_zan': 'Only the common user can thumb',
      'only_ordinary_users_can_create_posts': 'Only the common user can  publish topic',
      'oublish_post_success': 'Publish topic success',
      'title_content_must_not_null': 'The title and content can not be empty',
      'login': 'Login',
      'registered_account': 'Register Account',
      'forget_password': 'Forget Password',
      'please_input_old_pwd': 'Please input source password',
      'please_input_new_pwd': 'please input a new PWD with length between 6 and 12',
      'sure_update': 'Confirm Modify',
      'password_update_success': 'Modify Success',
      'title_update_password': 'Modify PWD',
      'please_input_nick_name': 'Please input  a nickname',
      'get_code': 'Get Captcha',
      'register_immediately': 'Register Now',
      'order_information_error': 'Order Info Error',
      'commodity_review_cannot_be_empty': 'The product comment can not be empty',
      'order_completed_evaluation': 'The comments of the order have finished ',
      'fail_to_comment': 'Submit comment not successful',
      'please_select_the_receiving_address': 'Please select the shipping address',
      'please_select_the_pay_type': 'Please select the pay type',
      'express_transportation': 'Express Transportation',
      'create_order_total_before': 'Sum',
      'create_order_total_after': 'pieces of product Total:',
      'freight_cost': 'Contain shipping fee¥',
      'order_has_create': 'The order have already been generated',
      'purchase_completed': 'Complete shopping',
      'available_integral_before': 'Can use',
      'available_integral_after': 'credits exchange ¥',
      'please_input_content': 'Please input the content',
      'fina_passwprd_success': 'Back PWD success,Login please',
      'user_name_pwd_not_null': 'The nickname and PWD can not been empty',
      'has_delect_this_addr': 'This shipping address have been deleted',
      're_acquisition': 'Get Again',
      'mobile_not_null': 'The mobile phone can not been empty',
      'password_must_be_greater_than': 'The length of the PWD should greater than 6',
      'verification_code_cannot_be_empty': 'The captcha can not been empty',
      'this_posts_has_delect_can_not_zan': 'This topic have been deleted,Can not thumb it',
      'this_posts_has_delect_can_not_comment': 'This topic have been deleted,Can not publish comment',
      'this_posts_has_delect': 'This topic have been deleted',
      'comment_success': 'Complete comment',
      'shopping_cart_product': 'Shopping Cart(Product)',
      'shopping_cart_credit': 'Shopping Cart(Credit Mall)',
      'please_login_before': 'Please login first',
      'activity_has_not_finish': 'The promotion have finished',
      'phone_call_false': 'Call failed',
      'problem_detail': 'Question Detail',
      'zhi': 'to',
      'recent_update': 'The latest update:',
      'come_back': 'Back',
      'route': 'Route',
      'scancode': 'Scan the QR code',
      'promotions': 'Promotion',
      'aready_checked': 'Already checked',
      'stock_num_before': 'Inventory',
      'stock_num_after': 'Pieces',
      'purchase_quantity_before': 'Limit Purchase',
      'purchase_quantity_after': 'Pieces',
      'article_center': 'Article Center',
      'commint_num': 'Comment',
      'integral_num': 'Credit',
      'growth_num': 'Growth Score',
      'shop_guide_advisory': 'I want to ask how to return goods',
      'shop_guide_other': 'Other questions',
      'address': 'Shipping Address',
      'wx_pay': 'WeChat Payment ',
      'ali_pay': 'Alipay',
      'um_pay': 'Pay on delivery ',
      'login_out': 'Logout',
      'my_member': 'My Members',
      'income_statement': 'Statement of income',
      'order_statement': 'Statement of order',
      'screen': 'Filter',
      'day_name_format': 'EEE',
      'invalid_date_before': 'The date must between',
      'invalid_date_middle': 'and',
      'month_name_format': 'MMMM yyyy',
      'member_count_before': 'Member Total(',
      'member_count_after': ')',
      'public_dis': 'Publish comment',
      'input_address': 'No address stored，where are you want to ship?',
      'pay_meth': 'Payment',
      'give_commodity': 'Gift',
      'distribution_meth': 'Shipping Method',
      'free_shipping': 'Free Shipping',
      'select_input': 'Optional，the remark of the order',
      'request': 'Request',
      'normal': 'Normal',
      'time': 'Time',
      'sale_value': 'Sales Volume',
      'prize': 'Price',
      'click_header_can_meet_me': 'Click the image to ask me',
      'reg_success': 'Register Success',
      'edit': 'Edit',
      'new_address': '+ New Address',
      'forum_header_number_before': 'Topic Num：',
      'forum_header_number_after': '          Reply Num：',
      'to_cast_before': 'Settlement（',
      'to_cast_after': '）',
      'growth_score_before': '+',
      'growth_score_after': 'Growth Score',
      'next_rank_before': 'Come to the next level need',
      'next_rank_after': 'Growth Score',
      'shop_car_is_null': 'The shoping cart is empty go to shopping now！',
      'complite_0': 'Finished(0)',
      'growth_value_detail': 'The statement of the growth score',
      'share_to_download': 'Share to your friends, scan the code to download quickly',
      'qr_tip': 'please set the barcode into the viewfinder to scan',
      'all_comments': '  All comments    ',
      'merchent_reply': 'Merchant Reply',
      'loading': 'Loading...',
      'number': 'Number',
      'do_you_select_guide': 'No shopping guide bound，go to choose?',
      'total_income': 'Sum earnings(RMB)',
      'order_total': 'Order Total(RMB)',
      'earnings_period': 'Period earnings(RMB)',
      'clear_filter_conditions': 'Clear the condition of the filter',
      'look_for_all_comments': 'View all of the comments',
      'pull_to_look_for_detail': 'Continue pull to view the  detail with words and pictures',
      'how_the_product': 'How about the product?Give me five star if satisfy~',
      'man': 'Up',
      'total_potion': 'Total Credits',
      'comment_hint': 'How about what the owner of the topic said? ',
      'select_form_album': 'Choose from album',
      'camera': 'Camera',
      'normal_order': 'Common Order',
      'integral_order': 'Credit Order',
      'select_pay_meth': 'Please select the payment',
      'screening_date': 'Filter the date',
      'no_items_selected': 'No product choose',
      'my_position': 'My Location',
      'failure_of_the_road': 'Programme the router failed',
      'key_validation_success': 'Validate the key success',
      'key_validation_failed': 'Validate the key fail',
      'invalid_mobile': 'Invalid mobile',
      'down_error_msg': 'Download fail, please create a directory named WDC at the root path of  your SD card, ten try again',
      'sorry_to_did_not_find_result': 'Sorry，No result got',
      'has_rob_num_before': 'Bought',
      'has_rob_num_after': 'Pieces',
      'grab_at_once': 'Buy Now  >',
      'jian1': 'Pieces',
      'rob_light': 'Out of incentory',
      'zhe': 'Discount',
      'yuan': 'RMB',
      'single_user_restriction': 'One user limit purchase',
      'has_sale_num_before': 'Sold',
      'has_sale_num_after': 'Pieces',
      'order_amount': 'Order Sum:',
      'order_credit': 'Credit Order:',
      'jian': 'Reduce',
      'song': 'Gift',
      'total_product_before': 'Total',
      'total_product_after': 'pieces of products    Sum:',
      'ship_prize_before': '(contain shipping fee',
      'ship_prize_after': ')',
      'please_install_wechat_client': 'Please download the client of the WeiChat first ',
      'integral_usage': 'Used Credits:',
      'most_select_num_before': 'Most can chose only ',
      'most_select_num_after': 'pictures',
      'atlast_select_one': 'Please at least chose one picture',
      'complete': 'Finished',
      'select_all': 'Select All',
      'has_not_sdcard': 'This mobile have no SD card',
      'order_gas_been_cancel': 'Order Canceled',
      'has_been_confirm_receipt': 'Confirm Receiving',
      'order_has_compilte': 'Finished Orders',
      'order_has_been_delect': 'Order have been deleted',
      'delect_of_order': 'Deleted Orders',
      'pay_complite': 'Pay complete',
      'commodity_information_acquisition_failure': 'Get Product  info Failed',
      'please_update': 'Please update to the latest version:',
      'promotion_product_inventory_shortage': 'The inventory of promotion product not enough',
      'credit_product_inventory_shortage': 'The inventory of credit product not enough',
      'inventory_shortage_to_buy': 'Inventory not enough,can not buy',
      'downloading': 'Downloading...',
      'cell_phone_number': 'Mobile',
      'image_up_fail': 'Upload picture fail',
      'please_enter_comments': 'Please input the content of the comment',
      'content_cannot_be_empty': 'The content of the comment can not be empty!',
      'verification_code_has_been_sent': 'The captcha have been send',
      'only_normal_user_can_into_shop_cart': 'Only the common user can join to the shopping cart',
      'click_to_load_more': 'Click to load more',
      'no_more_data': 'No more data',
      'enter_search_content': 'Please enter search content',
      'reduce_price': 'reduce price',
      'my_info': 'my info',
      'click_to_update': '(Click on the corresponding information to modify)',
      'head_portrait': 'Head portrait',
      'nickname': 'NickName',
      'enter_diff_nickname': 'Enter different user names',
      'sure_to_out': 'Do you want to quit?',
      'reset_password': 'Reset password',
      'sys': 'System',
      'sun': 'Sunday',
      'mon': 'Monday',
      'tues': 'Tuesday',
      'wed': 'Wednesday',
      'thurs': 'Thursday',
      'fri': 'Friday',
      'sat': 'Saturday',
      'year': 'Year',
      'month': 'Month',
      'start': 'Start',
      'end': 'End',
      'to': 'to',
      'no_comment': 'No Comment',
      'view_all_evaluations': 'view all evaluations',
      'express': 'express',
      'go_pay': 'Go Pay',
      'no_order': 'No Order',
      'please_pay_with_WeChat_scan_code': 'Please pay with WeChat scan code',
    },
    'zh': {
      'please_pay_with_WeChat_scan_code': '请使用微信扫码支付',
      'no_order': '暂无订单',
      'go_pay': '去支付',
      'express': '快递',
      'view_all_evaluations': '查看全部评价',
      'to': '到',
      'start': '开始',
      'end': '结束',
      'month': '月',
      'year': '年',
      'sun': '日',
      'mon': '一',
      'tues': '二',
      'wed': '三',
      'thurs': '四',
      'fri': '五',
      'sat': '六',
      'sys': '系统',
      'reset_password': '重设密码',
      'sure_to_out': '确定退出吗？',
      'enter_diff_nickname': '输入不同的用户名',
      'nickname': '昵称',
      'head_portrait': '头像',
      'click_to_update': '（点击相应信息即可修改）',
      'my_info': '我的资料',
      'enter_search_content': '请输入搜索内容',
      'no_more_data': '没有更多的数据了',
      'click_to_load_more': '点击加载更多',
      'app_name': 'Appbuilder',
      'rmb': '¥',
      'pay_complete': '已完成支付',
      'has_new_version': '有新版本啦是否更新',
      'app_version_is_new': '当前已是最新版本',
      'select_TA': '选择TA',
      'select_guide': '您还未选择导购，是否前往选择',
      'login_success': '欢迎回来',
      'mobile_and_pwd_must_not_null': '手机号或密不能为空',
      'please_input_real_mobile': '请输入正确的手机号',
      'password_must_between': '密码需在6~12位之间',
      'register_success': '您已成功注册',
      'mobile_must_not_null': '手机号不能为空',
      'nickname_must_not_null': '昵称不能为空',
      'password_must_not_null': '密码不能为空',
      'please_input_captcha': '请输入验证码',
      'nickname_must_between': '昵称需在2~12位之间',
      'find_pwd_success': '您已找回密码',
      'pressed_again_exit': '再按一次退出程序',
      'home_page': '首页',
      'category': '品类',
      'forum': '论坛',
      'article': '文章',
      'mine': '我的',
      'in_the_mood_for_love': '花样年华',
      'share_app_content_before': '我正在使用',
      'share_app_content_after': '，一起来加入我们享受优惠吧',
      'wechat_client_not_installed': '您还未安装微信客户端',
      'share_to': '分享到',
      'circle_of_friends': '朋友圈',
      'qzone': 'QQ空间',
      'please_pull_up_down_to_select_area': '请上下滑动列表选择地区',
      'cancel': '取消',
      'good': '好',
      'sure': '确定',
      'update': '更新',
      'wechat': '微信',
      'tip': '提示',
      'day': '天',
      'hour': '时',
      'minute': '分',
      'second': '秒',
      'net_error': '咦?网络不见了,请检查网络后点击屏幕重新加载',
      'no_data': '当前没有数据哦~',
      'pay_success': '支付成功',
      'user_has_cancel': '用户已取消',
      'not_pass_auth': '未通过认证',
      'no_know_error': '未知错误',
      'pay_abnormal': '支付异常',
      'pay_cancel': '支付取消',
      'user_data_update_success': '用户信息已更新',
      'please_select_the_provincial_information': '请选择地区',
      'please_fill_in_the_details': '请输入详细地址',
      'please_fill_in_the_name_of_the_consignee': '请输入收货人姓名',
      'please_contact_the_consignee': '请输入收货人联系电话',
      'please_input_the_postzip': '请输入邮编',
      'postzip': '邮编',
      'addr_name': '姓  名',
      'addr_phone': '电  话',
      'local_area': '所在地区',
      'detailed_address': '详细地址',
      'default_address': '默认地址',
      'delect_address': '删除地址',
      'save': '保存',
      'addr_has_been_save': '收货地址保存成功',
      'addr_has_been_update': '收货地址修改成功',
      'find': '发现',
      'promotion': '促销',
      'branch': '分店',
      'integral_mall': '积分商城',
      'want_to_buy_something_today': '今天想买点什么',
      'product_information': '产品信息',
      'product_detail_all_comment_before': '宝贝评价(',
      'product_detail_all_comment_after': ')',
      'graphic_details': '图文详情',
      'product_spec': '产品规格',
      'add_shop_car': '加入购物车',
      'buy_immediately': '立即购买',
      'has_add_shop_car': '已加入购物车',
      'has_rob_count_before': '已抢',
      'has_not_rob': '即将开始',
      'has_rob': '马上抢',
      'has_rob_clear': '已抢光',
      'shop_car_product': '购物车(产品)',
      'shop_car_integral_mall': '购物车(积分商城)',
      'product': '产品',
      'shop_car_total': '合计:',
      'not_ship': '(不含运费)',
      'shop_car_settlement_before': '结算(',
      'shop_car_settlement_after': ')',
      'this_product_has_delect': '该产品已删除',
      'comment': '评论',
      'integral': '积分',
      'growth_value': '成长值',
      'my_order': '我的订单',
      'my_shopping_guide': '我的导购',
      'receipt_address': '收货地址',
      'my_post': '我的帖子',
      'complaints_and_suggestions': '投诉建议',
      'all': '全部',
      'not_paid': '未支付',
      'already_paid': '已支付',
      'payment_failure': '支付失败',
      'already_shipped': '已发货',
      'cash_on_delivery': '货到付款',
      'has_been_canceled': '已取消',
      'has_been_completed': '已完成',
      'expired': '已过期',
      'order_number': '订单编号',
      'a_total_of_items_a_total_of_before': '共',
      'a_total_of_items_a_total_of_after': '件商品   合计:',
      'freight': '含运费',
      'cancellation_of_order': '取消订单',
      're_payment': '重新支付',
      'confirm_receipt': '确认收货',
      'delect_order': '删除订单',
      'immediate_evaluation': '立即评价',
      'haven_not_received_the_goods_address_oh': '还没有收货地址哦',
      'add_a_new_address': '添加新地址',
      'is_delect_the_address': '是否删除该收货地址',
      'is_cancel_order': '是否取消订单',
      'is_confirm_receipt': '是否确认收货',
      'is_delect_order': '是否要删除订单',
      'setting': '设置',
      'about_store': '关于门店',
      'check_for_updates': '检查更新',
      'wipe_cache': '清空缓存',
      'set_share': '分享给朋友,扫描快速下载',
      'current_version': '当前版本',
      'currently_is_the_latest_version': '当前已是最新版本',
      'whether_to_clear_the_cache': '是否清除缓存',
      'growth': '成长值',
      'message': '消息',
      'my_comments': '我的评论',
      'my_points': '我的积分',
      'current_level': '当前等级',
      'points_of_balance': '积分收支明细',
      'distance_to_the_next_level_before': '距离下一等级还需',
      'distance_to_the_next_level_after': '成长值',
      'click_on_the_header': '点击头像即可咨询我哦',
      'change_guide': '更换导购',
      'message_remarks': '留言备注',
      'logistics_mode': '物流方式',
      'number_of_logistics': '物流单号',
      'integral_number': '使用积分数',
      'sumulative_consumption_points': '本次消费累计积分',
      'order_time': '下单时间',
      'real_payment': '实付款',
      'publish_hint': '发布',
      'dis': '评论',
      'please_input_what_you_feedback': '输入你想反馈的内容',
      'send': '发送',
      'title_activity_main': 'MainActivity',
      'title_activity_http': '网络请求',
      'title_activity_img_bower': 'ImgBowerActivity',
      'title_activity_pull_refresh': 'PullRefreshActivity',
      'title_activity_start': 'appbuilder',
      'title_activity_store_detail': '门店详情',
      'title_activity_product_detail': '产品详情',
      'title_activity_shop_cart': '购物车',
      'title_activity_forget_password': '找回密码',
      'title_activity_login': '登录',
      'title_activity_update_password': '修改密码',
      'title_activity_register': '注册',
      'title_activity_search': '搜索',
      'title_activity_forum_list': '帖子列表',
      'title_activity_publish_forum': '发布帖子',
      'title_activity_account_setting': '个人设置',
      'title_activity_user_rank': '当前等级',
      'title_activity_user_order': '我的订单',
      'title_activity_user_address': '收货地址',
      'title_activity_add_newAddress': '新增收货地址',
      'title_activity_modify_address': '编辑地址',
      'title_activity_feedback': '投诉建议',
      'title_activity_userArticle': '我的帖子',
      'title_activity_choosePlace': '选择地区',
      'title_activity_create_order': '提交订单',
      'title_activity_forumDetails': '帖子详情',
      'title_activity_articleDetails': '文章详情',
      'title_activity_shopGuide': '导购',
      'title_activity_chooseGuide': '选择分店',
      'title_activity_userSetting': '设置',
      'title_activity_orderDetail': '订单详情',
      'title_activity_userCommit': '我的评论',
      'title_activity_product_list': '产品列表',
      'title_activity_article_list': '文章列表',
      'title_activity_calendar': '日期选择',
      'title_activity_my_member': '我的会员',
      'title_activity_commit_list': '评论列表',
      'add_receipt_address': '新增收货地址',
      'modify_address_information': '修改地址信息',
      'the_receipt_address_has_been_deleted': '该收货地址已删除',
      'comment_publish_success': '评论发布成功',
      'current_points': '当前积分',
      'item_merchent_reply': '商户回复',
      'the_posts_has_been_delect': '该帖已删除',
      'only_normal_user_can_zan': '只有普通用户才能进行点赞',
      'only_normal_user_can_buy': '只有普通用户才能进行购买',
      'only_normal_user_can_add_shop_cart': '只有普通用户才能加入购物车',
      'cancel_zan': '取消点赞',
      'has_been_zan': '已赞',
      'number_of_participants': '人参与',
      'post': '帖子',
      'replies': '回帖',
      'publish_post': '发帖',
      'thumb_number': '人赞了',
      'post_detail': '帖子详情',
      'all_post_comment_before': '全部跟帖(',
      'all_post_comment_after': ')',
      'activity_publish_post': '发布帖子',
      'publish_post_title_hint': '编写帖子标题',
      'publish_post_content_hint': '编写帖子内容',
      'classification': '分类',
      'new_arrival': '新品上市',
      'distance_events_start': '距离活动开始:',
      'distance_events_end': '距离活动结束:',
      'integral_not_enough': '积分不足',
      'convertible': '可兑换',
      'please_input_mobile': '请输入手机号',
      'please_input_password': '请输入6~12位的密码',
      'reg': '注册',
      'only_ordinary_users_can_comment': '只有普通用户才可以评论',
      'only_ordinary_users_can_zan': '只有普通用户才可以点赞',
      'only_ordinary_users_can_create_posts': '只有普通用户才可以发帖',
      'oublish_post_success': '发表帖子成功',
      'title_content_must_not_null': '标题或内容不能为空',
      'login': '登录',
      'registered_account': '注册账号',
      'forget_password': '忘记密码',
      'please_input_old_pwd': '请输入旧密码',
      'please_input_new_pwd': '请输入6~12位的新密码',
      'sure_update': '确认修改',
      'password_update_success': '密码修改成功',
      'title_update_password': '修改密码',
      'please_input_nick_name': '请输入昵称',
      'get_code': '获取验证码',
      'register_immediately': '立即注册',
      'order_information_error': '订单信息错误',
      'commodity_review_cannot_be_empty': '商品评论不能为空',
      'order_completed_evaluation': '订单已完成评价',
      'fail_to_comment': '未能成功评论',
      'please_select_the_receiving_address': '请选择收货地址',
      'please_select_the_pay_type': '请选择支付方式',
      'express_transportation': '快递运输',
      'create_order_total_before': '共',
      'create_order_total_after': '件商品 合计:',
      'freight_cost': '含运费¥',
      'order_has_create': '订单已生成',
      'purchase_completed': '购买完成',
      'available_integral_before': '可用',
      'available_integral_after': '积分抵¥',
      'please_input_content': '请输入内容',
      'fina_passwprd_success': '找回密码成功,请登录',
      'user_name_pwd_not_null': '用户名和密码不能为空',
      'has_delect_this_addr': '已删除该收货地址',
      're_acquisition': '重新获取',
      'mobile_not_null': '手机号不能为空',
      'password_must_be_greater_than': '密码必须大于6位',
      'verification_code_cannot_be_empty': '验证码不能为空',
      'this_posts_has_delect_can_not_zan': '该帖子已删除,无法进行点赞',
      'this_posts_has_delect_can_not_comment': '该帖子已删除,无法进行评论',
      'this_posts_has_delect': '该帖已删除',
      'comment_success': '已完成评论',
      'shopping_cart_product': '购物车(产品)',
      'shopping_cart_credit': '购物车(积分商城)',
      'please_login_before': '请先登录',
      'activity_has_not_finish': '活动已结束',
      'phone_call_false': '电话拨打失败',
      'problem_detail': '问题详情',
      'zhi': '至',
      'recent_update': '最近更新:',
      'come_back': 'Back',
      'route': '路径',
      'scancode': '扫描二维码',
      'promotions': '促销',
      'aready_checked': '已选',
      'stock_num_before': '库存',
      'stock_num_after': '件',
      'purchase_quantity_before': '限购',
      'purchase_quantity_after': '件',
      'article_center': '文章中心',
      'commint_num': '评论',
      'integral_num': '积分',
      'growth_num': '成长值',
      'shop_guide_advisory': '我要咨询如何退货',
      'shop_guide_other': '其它问题',
      'address': '收货地址',
      'wx_pay': '微信支付',
      'ali_pay': '支付宝支付',
      'um_pay': '货到付款',
      'login_out': '退出账号',
      'my_member': '我的会员',
      'income_statement': '收益明细',
      'order_statement': '订单明细',
      'screen': '筛选',
      'day_name_format': 'EEE',
      'invalid_date_before': '日期必须在',
      'invalid_date_middle': '和',
      'invalid_date_after': '期间',
      'month_name_format': 'MMMM yyyy',
      'member_count_before': '会员总数(',
      'member_count_after': ')',
      'public_dis': '发表评价',
      'input_address': '地址都没有添加，要寄去哪里呢',
      'pay_meth': '支付方式',
      'give_commodity': '赠送商品',
      'distribution_meth': '配送方式',
      'free_shipping': '免邮',
      'select_input': '选填，可输入备注',
      'request': '请求',
      'normal': '普通',
      'time': '时间',
      'sale_value': '销量',
      'prize': '价格',
      'click_header_can_meet_me': '点击头像可以咨询我哦',
      'reg_success': '注册成功',
      'edit': '编辑',
      'new_address': '+ 新增地址',
      'forum_header_number_before': '帖子数：',
      'forum_header_number_after': '          回帖数：',
      'to_cast_before': '去结算（',
      'to_cast_after': '）',
      'growth_score_before': '+',
      'growth_score_after': '成长值',
      'next_rank_before': '距离一下等级还需',
      'next_rank_after': '成长值',
      'shop_car_is_null': '购物车空空如也快去挑选好货吧！',
      'complite_0': '完成(0)',
      'growth_value_detail': '成长值明细',
      'share_to_download': '分享给朋友,扫码快速下载',
      'qr_tip': '请将条码置于取景框内扫描。',
      'all_comments': '  全部评论    ',
      'merchent_reply': '商家回复',
      'loading': '正在加载中...',
      'number': '数量',
      'do_you_select_guide': '您还未绑定导购，是否前去选择',
      'total_income': '累计收益(元)',
      'order_total': '订单总额(元)',
      'earnings_period': '期间收益(元)',
      'clear_filter_conditions': '清除筛选条件',
      'look_for_all_comments': '查看全部评论',
      'pull_to_look_for_detail': '继续拖动，查看图文详情',
      'how_the_product': '产品怎么样？满意5分好评哦~',
      'man': '满',
      'total_potion': '总分',
      'comment_hint': '楼主说得怎么样，点评一下',
      'select_form_album': '从相册选择',
      'camera': '相机',
      'normal_order': '普通订单',
      'integral_order': '积分订单',
      'select_pay_meth': '选择支付方式',
      'screening_date': '筛选日期',
      'no_items_selected': '未选中任何商品',
      'my_position': '我的位置',
      'failure_of_the_road': '算路失败',
      'key_validation_success': 'key校验成功',
      'key_validation_failed': 'key校验失败',
      'invalid_mobile': '无效的手机号码',
      'down_error_msg': '下载失败,请在SD卡根目录下创建 WDC 文件夹,再尝试下载',
      'sorry_to_did_not_find_result': '抱歉，未找到结果',
      'has_rob_num_before': '已抢',
      'has_rob_num_after': '件',
      'grab_at_once': '马上抢  >',
      'jian1': '件',
      'rob_light': '抢光了',
      'zhe': '折',
      'yuan': '元',
      'single_user_restriction': '单用户限购',
      'has_sale_num_before': '已售',
      'has_sale_num_after': '件',
      'order_amount': '订单金额:',
      'order_credit': '订单积分:',
      'jian': '减',
      'song': '送',
      'total_product_before': '共',
      'total_product_after': '件商品    合计:',
      'ship_prize_before': '(含运费',
      'ship_prize_after': ')',
      'please_install_wechat_client': '请先安装微信客户端',
      'integral_usage': '积分使用数:',
      'most_select_num_before': '最多只能选择',
      'most_select_num_after': '张图片',
      'atlast_select_one': '至少选择一张图片',
      'complete': '完成',
      'select_all': '全选',
      'has_not_sdcard': '该手机没有内存卡',
      'order_gas_been_cancel': '订单已取消',
      'has_been_confirm_receipt': '已确认收货',
      'order_has_compilte': '已完成订单',
      'order_has_been_delect': '订单已删除',
      'delect_of_order': '已删除订单',
      'pay_complite': '支付完成',
      'commodity_information_acquisition_failure': '商品信息获取失败',
      'please_update': '请更新到最新版本:',
      'promotion_product_inventory_shortage': '促销产品库存不足',
      'credit_product_inventory_shortage': '积分产品库存不足',
      'inventory_shortage_to_buy': '库存不足,无法购买',
      'downloading': '下载中...',
      'cell_phone_number': '手机号',
      'image_up_fail': '图片上传失败',
      'please_enter_comments': '请输入评论内容',
      'content_cannot_be_empty': '评论内容不能为空!',
      'verification_code_has_been_sent': '验证码已发送',
      'only_normal_user_can_into_shop_cart': '只有普通用户才能进入购物车',
      'reduce_price': '减价',
      'delete': '删除',
      'no_comment': '暂无评价',
    }
  };

  transform(value: any, args?: any): string {
    const lang = navigator.language.substring(0, 2);
    return this._wordBook[lang][value];
  }

}
